config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
  root "dashboards#index"

  resources :reels

  resources :clips

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/clip.rb
class Clip < ApplicationRecord
end

app/models/reel.rb
class Reel < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
    def index
        @clips = Clip.all
    end
  
    # Add other CRUD actions as needed
   
    private
   
    def clip_params
        params.require(:clip).permit(:name, :video_standard, :video_definition, :start_time, :end_time, :description)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    def index
    end
end
  

app/controllers/reels_controller.rb
class ReelsController < ApplicationController
    before_action :set_reel, only: [:show, :edit, :update, :destroy]
    
    def index
        @reels = Reel.all
    end
  
    def show
        @added_clips = Clip.where(id: conv_arr(@reel.clip_list)) 
    end
  
    def new
        @reel = Reel.new
        @clips = Clip.all
    end

    def create
        @reel = Reel.new(reel_params)

        @reel.total_play_time = calc_total_play_time(reel_params[:video_standard], params[:clip_times])
            
        if @reel.save
            redirect_to @reel, notice: 'Reel was successfully created.'
        else
            render :new
        end
    end
    
    def edit
        @added_clips = Clip.where(id: conv_arr(@reel.clip_list)) 
        @rest_clips = Clip.where.not(id: conv_arr(@reel.clip_list)) 
    end 

    def update
        @reel.total_play_time = calc_total_play_time(reel_params[:video_standard], params[:clip_times])

        if @reel.update(reel_params)
            redirect_to @reel, notice: 'Reel was successfully updated.'
        else
            render :edit
        end
    end
    
    def destroy
        @reel.destroy
        redirect_to reels_url, notice: 'Reel was successfully destroyed.'
    end
    
    private

    def set_reel
        @reel = Reel.find(params[:id])
    end

    def conv_arr(str)
        return str.split(',').map(&:to_i)
    end

    def calc_total_play_time(video_standard, clip_times)
        fps_per_secs = (video_standard === 'PAL') ? 1.0/25 : 1.0/30
        clip_times = clip_times.split(',').map(&:to_s)
        total_secs = 0.0
        clip_times.each do |clip_time|
            time_array = clip_time.split(':').map(&:to_i)
            time_secs = time_array[0] * 3600 + time_array[1] * 60 + time_array[2] + time_array[3] * fps_per_secs
            total_secs += time_secs
        end

        hrs = total_secs.to_i / (60 * 60)
        mins = (total_secs.to_i / 60) % 60
        secs = total_secs.to_i % 60
        f_secs = total_secs % 1
        ffs = (f_secs / fps_per_secs).round

        return "#{sprintf("%02d", hrs)}:#{sprintf("%02d", mins)}:#{sprintf("%02d", secs)}:#{sprintf("%02d", ffs)}"
    end
    
    def reel_params
        params.require(:reel).permit(:name, :video_standard, :video_definition, :clip_list)
    end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/helpers/reels_helper.rb
module ReelsHelper
end

app/views/clips/index.html.erb
<div class="row p-3">
  <h2>All Clips</h2>

  <table class="table table-hover table-responsive table-bordered">
    <tr class="table-light">
      <th>Name</th>
      <th>Description</th>
      <th>Video Standard</th>
      <th>Video Definition</th>
      <th>Start Time</th>
      <th>End Time</th>
    </tr>
    <% @clips.each do |clip| %>
      <tr>
        <td><%= clip.name %></td>
        <td><%= clip.description %></td>
        <td><%= clip.video_standard %></td>
        <td><%= clip.video_definition %></td>
        <td><%= clip.start_time %></td>
        <td><%= clip.end_time %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/dashboards/index.html.erb
<div class="row p-3">
    <h2>Welcom to visit our application!</h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reels</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'bootstrap.min', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'jquery-ui.min', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'jquery.min', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'jquery-ui.min', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |key, value| %>
  <div class="alert alert-notice alert-success">
    <%= value %>
  </div>
<% end %>

    <header>
      <% paths = request.path.split('/') %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <%= link_to 'Dashboard', root_path, class: "navbar-brand" %>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to 'Reels', reels_path, class: "nav-link #{ paths[1] === 'reels' ? 'active' : '' }" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Clips', clips_path,class: "nav-link #{ paths[1] === 'clips' ? 'active' : '' }" %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

<script>
$(document).ready(function() {
  $(".alert-notice").delay(2000).fadeOut();
});

</script>

app/views/reels/edit.html.erb
<div class="row p-3">
    <h2>Edit Reel</h2>

    <%= form_with(model: @reel, class: 'row g-3 needs-validation', url: reel_path(@reel), method: :patch) do |form| %>
        <%= form.hidden_field :clip_list, id: 'clip_list' %>
        <input type="hidden" name="clip_times" id="clip_times">
        
        <div class="col-md-12">
            <div class="col-md-4 offset-md-4">
                <%= form.label :name, class: 'form-label' %>
                <%= form.text_field :name, class: 'form-control', required: true %>
            </div>
        </div>

        <div class="col-md-12">
            <div class="col-md-4 offset-md-4">
                <%= form.label :video_standard, class: 'form-label' %>
                <%= form.select :video_standard, [['PAL', 'PAL'], ['NTSC', 'NTSC']], { prompt: 'Select ...' }, { class: 'form-select video_standard_select', required: true } %>
            </div>
        </div>

        <div class="col-md-12">
            <div class="col-md-4 offset-md-4">
                <%= form.label :video_definition, class: 'form-label' %>
                <%= form.select :video_definition, [['SD', 'SD'], ['HD', 'HD']], { prompt: 'Select ...' }, { class: 'form-select video_definition_select', required: true } %>
            </div>
        </div>

        <div class="col-md-12">
            <div class="col-md-8 offset-md-4">
                <div class="row col-md-12">
                    <div class="col-md-6">
                        <label>Added Clips</label>
                        <ul id="addedClips" class="form-control">
                            <% @added_clips.each do |clip| %>
                                <li class="form-control clip_item"
                                 data-id="<%= clip.id %>"
                                 data-standard="<%= clip.video_standard %>"
                                 data-definition="<%= clip.video_definition %>"
                                 data-endtime="<%= clip.end_time %>"
                                >
                                    <span><%= clip.name %></span>
                                    <span>(<%= clip.video_standard %> |</span>
                                    <span><%= clip.video_definition %> |</span>
                                    <span class="float-right"><%= clip.end_time %>)</span>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <label>All Clips</label>
                        <ul id="allClips" class="form-control">
                            <% @rest_clips.each do |clip| %>
                                <li class="form-control clip_item"
                                 data-id="<%= clip.id %>"
                                 data-standard="<%= clip.video_standard %>"
                                 data-definition="<%= clip.video_definition %>"
                                 data-endtime="<%= clip.end_time %>"
                                >
                                    <span><%= clip.name %></span>
                                    <span>(<%= clip.video_standard %> |</span>
                                    <span><%= clip.video_definition %> |</span>
                                    <span class="float-right"><%= clip.end_time %>)</span>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>

            </div>
        </div>

        <div class="col-md-12">
            <div class="col-md-4 offset-md-4">
                <label class="form-label">Total Play Time</label>
                <input type="text" class="form-control mb-3" value="<%= @reel.total_play_time %>" readonly>
            </div>
        </div>

        <div class="col-md-12">
            <div class="col-md-2 offset-md-4">
                <%= form.submit 'Upate Reel', class: 'btn btn-success' %>
                <%= link_to 'Cancel', reels_path(@reel), class: 'btn btn-secondary' %>
            </div>
        </div>
    <% end %>
</div>

<script>
    $(function() {
        $("#addedClips, #allClips").sortable ({
            connectWith: "ul",
            placeholder: "placeholder",
            delay: 150,
            receive: function() {
                updateClipsIds();
            }
        })
        .disableSelection ()
        .dblclick( function(e) {
            var item = e.target;
            if (e.currentTarget.id === 'addedClips') {
                $(item).fadeOut('fast', function() {
                    $(item).appendTo($('#allClips')).fadeIn('slow');
                });
            } else {
                $(item).fadeOut('fast', function() {
                    $(item).appendTo($('#addedClips')).fadeIn('slow');
                });
            }
        });
    });

    var standard_value = $('#reel_video_standard').val();
    var definition_value = $('#reel_video_definition').val();

    $(document).ready(function() {

        displayClips();
        updateClipsIds();

        $('.video_standard_select').change(function() {
            standard_value = $(this).val();
            
            displayClips();
            updateClipsIds();
        });

        $('.video_definition_select').change(function() {
            definition_value = $(this).val();

            displayClips();
            updateClipsIds();
        });
    });

    function displayClips() {
        var elements = $(".clip_item");
        
        elements.addClass("display_none");
        
        if (standard_value !== '' && definition_value !== '') {
                elements = $(".clip_item[data-standard='" + standard_value + "'][data-definition='" + definition_value + "']");
        } else if (standard_value === '' && definition_value !== '') {
            elements = $(".clip_item[data-definition='" + definition_value + "']");
        } else if (standard_value !== '' && definition_value === '') {
            elements = $(".clip_item[data-standard='" + standard_value + "']");
        } else {
            elements = $(".clip_item");
        }

        elements.removeClass("display_none");
    }

    function updateClipsIds() {
        var clip_ids = [];
        var clip_times = [];

        var added_elements = $("ul#addedClips").find("li:visible");
        added_elements.each(function () {
            clip_ids.push($(this).attr('data-id'));
            clip_times.push($(this).attr('data-endtime'));
        });

        $("#clip_list").val(clip_ids);
        $("#clip_times").val(clip_times);
    }

</script>

app/views/reels/index.html.erb
<div class="row p-3">
  <h2>All Reels</h2>

  <div class="col-md-2 p-3">
  <%= link_to '+ New Reel', new_reel_path, class: 'btn btn-primary' %>
  </div>

  <table class="table table-hover table-responsive table-bordered">
    <tr class="table-light">
      <th>Name</th>
      <th>Video Standard</th>
      <th>Video Definition</th>
      <th>Total Play Time</th>
      <th>Action</th>
    </tr>
    <% @reels.each do |reel| %>
      <tr>
        <td><%= reel.name %></td>
        <td><%= reel.video_standard %></td>
        <td><%= reel.video_definition %></td>
        <td><%= reel.total_play_time %></td>
        <td>
          <%= link_to 'Show', reel_path(reel), class: 'btn btn-warning' %>
          <%= link_to 'Edit', edit_reel_path(reel), class: 'btn btn-info' %>
          <%= button_to "Delete", reel_path(reel), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/reels/new.html.erb
<div class="row p-3">
    <h2>Create a New Reel</h2>

    <%= form_with(model: @reel, class: 'row g-3 needs-validation', url: reels_path) do |form| %>
        <%= form.hidden_field :clip_list, id: 'clip_list' %>
        <input type="hidden" name="clip_times" id="clip_times">
        
        <div class="col-md-12">
            <div class="col-md-4 offset-md-4">
                <%= form.label :name, class: 'form-label' %>
                <%= form.text_field :name, class: 'form-control', required: true %>
            </div>
        </div>

        <div class="col-md-12">
            <div class="col-md-4 offset-md-4">
                <%= form.label :video_standard, class: 'form-label' %>
                <%= form.select :video_standard, options_for_select([['PAL', 'PAL'], ['NTSC', 'NTSC']]), { prompt: 'Select ...' }, { class: 'form-select video_standard_select', required: true } %>
            </div>
        </div>

        <div class="col-md-12">
            <div class="col-md-4 offset-md-4">
                <%= form.label :video_definition, class: 'form-label' %>
                <%= form.select :video_definition, options_for_select([['SD', 'SD'], ['HD', 'HD']]), { prompt: 'Select ...' }, { class: 'form-select video_definition_select', required: true } %>
            </div>
        </div>

        <div class="col-md-12">
            <div class="col-md-8 offset-md-4">
                <div class="row col-md-12">
                    <div class="col-md-6">
                        <label>Added Clips</label>
                        <ul id="addedClips" class="form-control">
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <label>All Clips</label>
                        <ul id="allClips" class="form-control">
                            <% @clips.each do |clip| %>
                                <li class="form-control clip_item"
                                 data-id="<%= clip.id %>"
                                 data-standard="<%= clip.video_standard %>"
                                 data-definition="<%= clip.video_definition %>"
                                 data-endtime="<%= clip.end_time %>"
                                >
                                    <span><%= clip.name %></span>
                                    <span>(<%= clip.video_standard %> |</span>
                                    <span><%= clip.video_definition %> |</span>
                                    <span class="float-right"><%= clip.end_time %>)</span>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>

            </div>
        </div>

        <div class="col-md-12">
            <div class="col-md-2 offset-md-4">
                <%= form.submit 'Create Reel', class: 'btn btn-success' %>
                <%= link_to 'Back', reels_path, class: 'btn btn-secondary' %>
            </div>
        </div>
    <% end %>
</div>

<script>
    $(function() {
        $("#addedClips, #allClips").sortable ({
            connectWith: "ul",
            placeholder: "placeholder",
            delay: 150,
            receive: function() {
                updateClipsIds();
            }
        })
        .disableSelection ()
        .dblclick( function(e) {
            var item = e.target;
            if (e.currentTarget.id === 'addedClips') {
                $(item).fadeOut('fast', function() {
                    $(item).appendTo($('#allClips')).fadeIn('slow');
                });
            } else {
                $(item).fadeOut('fast', function() {
                    $(item).appendTo($('#addedClips')).fadeIn('slow');
                });
            }
        });
    });

    var standard_value = '';
    var definition_value = '';

    $(document).ready(function() {
        $('.video_standard_select').change(function() {
            standard_value = $(this).val();
            
            displayClips();
            updateClipsIds();
        });

        $('.video_definition_select').change(function() {
            definition_value = $(this).val();

            displayClips();
            updateClipsIds();
        });
    });

    function displayClips() {
        var elements = $(".clip_item");
        
        elements.addClass("display_none");
        
        if (standard_value !== '' && definition_value !== '') {
                elements = $(".clip_item[data-standard='" + standard_value + "'][data-definition='" + definition_value + "']");
        } else if (standard_value === '' && definition_value !== '') {
            elements = $(".clip_item[data-definition='" + definition_value + "']");
        } else if (standard_value !== '' && definition_value === '') {
            elements = $(".clip_item[data-standard='" + standard_value + "']");
        } else {
            elements = $(".clip_item");
        }

        elements.removeClass("display_none");
    }

    function updateClipsIds() {
        var clip_ids = [];
        var clip_times = [];

        var added_elements = $("ul#addedClips").find("li:visible");
        added_elements.each(function () {
            clip_ids.push($(this).attr('data-id'));
            clip_times.push($(this).attr('data-endtime'));
        });

        $("#clip_list").val(clip_ids);
        $("#clip_times").val(clip_times);
    }

</script>

app/views/reels/show.html.erb
<div class="row p-3">
    <h2>Reel Details</h2>

    <div class="col-md-12">
        <div class="col-md-4 offset-md-4">
            <label class="form-label">Name</label>
            <input type="text" class="form-control" value="<%= @reel.name %>" readonly>
        </div>
    </div>

    <div class="col-md-12">
        <div class="col-md-4 offset-md-4">
            <label class="form-label">Video Standard</label>
            <input type="text" class="form-control" value="<%= @reel.video_standard %>" readonly>
        </div>
    </div>

    <div class="col-md-12">
        <div class="col-md-4 offset-md-4">
            <label class="form-label">Video Definition</label>
            <input type="text" class="form-control" value="<%= @reel.video_definition %>" readonly>
        </div>
    </div>

    <div class="col-md-12">
        <div class="col-md-8 offset-md-4">
            <div class="row col-md-12">
                <div class="col-md-6">
                    <label>Added Clips</label>
                    <ul id="addedClips" class="form-control">
                        <% @added_clips.each do |clip| %>
                            <li class="form-control clip_item"
                                data-id="<%= clip.id %>"
                                data-standard="<%= clip.video_standard %>"
                                data-definition="<%= clip.video_definition %>"
                                data-endtime="<%= clip.end_time %>"
                            >
                                <span><%= clip.name %></span>
                                <span>(<%= clip.video_standard %> |</span>
                                <span><%= clip.video_definition %> |</span>
                                <span class="float-right"><%= clip.end_time %>)</span>
                            </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="col-md-4 offset-md-4">
            <label class="form-label">Total Play Time</label>
            <input type="text" class="form-control mb-3" value="<%= @reel.total_play_time %>" readonly>
        </div>
    </div>

    <div class="col-md-12">
        <div class="col-md-2 offset-md-4">
            <%= link_to 'Edit', edit_reel_path(@reel), class: "btn btn-info" %>
            <%= link_to 'Back', reels_path, class: "btn btn-secondary" %>
        </div>
    </div>
</div>